# Versão do Ubuntu
os: linux
dist: focal

addons:
  sonarcloud:
    organization: iammateus
    token: ${SONAR_TOKEN}

# Linguagem Utilizada para Desenvolver a Aplicação                                                                                                                                                       
language: python                                                                                                                                                                                         

# Versão que a aplicação suporta.                                                                                                                                                                        
python:                                                                                                                                                                                                  
  - "3.8"                                                                                                                                                                                              

# Instalação de Módulos que são necessários para a Aplicação.                                                                                                                                            
install:                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
  - pip install flask pytest flask-wtf coverage

# Defini o script de Teste que deve rodar toda vez que o código for alterado.                                                                                                                            
script:                                                                                                                                                                                                  
  - coverage run -m pytest test.py || travis_terminate 1;
  - coverage report app.py || travis_terminate 1;
  - coverage xml app.py || travis_terminate 1;                                                                                                                                                                                         
  - sonar-scanner || travis_terminate 1;

# Definir o Deploy no Heroku
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true 
  app: iammateus-devopslab-es21
  on:
      branch: main